### PR TITLE
Known bug links: Search all `site-report`s, not just things in the WebCompat component.

### LINKED ISSUE #36: Add second "list of bugs" link for all components
The current link just shows bugs in the WebCompat component, but we sometimes have known-open Core Bugs we want to link to, too.

### PR DESCRIPTION
**Pull request by denschub**
This resolves #36, but instead of adding a second link, I figured it's best to just search the entirety of Bugzilla for `webcompat:site-report` marked bugs, as opposed to limiting it to specific components. We encourage engineers to move bugs into their own components as long as they have the site-report keyword, and this matches what we'd display with a bug-list inline.

r? @jgraham

### CODE REVIEW

File: server/frontend/src/components/Buckets/View.vue [hunk 1]
```diff
@@ -351,22 +351,9 @@ export default {
...
-        ["f4", "CP"],
-        ["f5", "OP"],
-        ["o6", "equals"],
-        ["f6", "product"],
-        ["v6", "Web Compatibility"],
-        ["o7", "equals"],
-        ["f7", "component"],
-        ["v7", "Privacy: Site Reports"],
-        ["f8", "CP"],
+        ["o1", "substring"],
```
Comment (jgraham) [inline server/frontend/src/components/Buckets/View.vue:354]: I think you should also search in Web Compatibility :: [Privacy] Site Report components, otherwise bugs won't show up until they have been triaged.

**Review by jgraham — CHANGES_REQUESTED** [review]

File: server/frontend/src/components/Buckets/View.vue (hunk 1 above)
Comment (denschub) [reply server/frontend/src/components/Buckets/View.vue]: Most of the bugs in there were created by SV, so they all have the keyword, so I ignored that. But you're right, there's no reason not to include them. Instead of replacing the entire query, I just added another matching row to the "any" group, so it now looks like this:

Screenshot 2025-04-24 at 16 11 23

**Review by jgraham — APPROVED** [review]
